name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git user name and email
      run: |
        git config --global user.name "Andrew Stelmach"
        git config --global user.email "${{ secrets.EMAIL }}"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/Torantulino/Auto-GPT.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes into master branch
      run: git merge upstream/master

    - name: Push changes to fork
      run: git push origin master

